steps:
  # 0. Create Artifact Registry repository if it doesn't exist
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud artifacts repositories create stream-watcher \
          --repository-format=docker \
          --location=us-central1 \
          --description="Stream Watcher repository for UI and proxy images" || true

  # 1. Use Docker for linting and testing (eliminates duplicate npm install)
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    env:
      - 'DOCKER_BUILDKIT=1'
    args:
      - '-c'
      - |
        # Pull cache image first
        docker pull us-central1-docker.pkg.dev/$PROJECT_ID/stream-watcher/ui-proxy:latest || true
        
        # Build test stage only (stops at ui-builder stage for faster testing)
        docker build \
          --target ui-builder \
          --tag test-image \
          --cache-from us-central1-docker.pkg.dev/$PROJECT_ID/stream-watcher/ui-proxy:latest \
          --build-arg FIREBASE_BUILD_ENV="$$FIREBASE_BUILD_ENV" \
          --build-arg VITE_FIREBASE_PROJECT_ID=$PROJECT_ID \
          .
        
        # Run linting and tests in parallel
        docker run --rm test-image npm run lint &
        docker run --rm test-image npm test &
        
        # Wait for both to complete
        wait
    secretEnv:
      - 'FIREBASE_BUILD_ENV'

  # 2. Build production Docker image (reuses cache from step 1)
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    env:
      - 'DOCKER_BUILDKIT=1'
    args:
      - '-c'
      - |
        docker build \
          --tag 'us-central1-docker.pkg.dev/$PROJECT_ID/stream-watcher/ui-proxy:$SHORT_SHA' \
          --tag 'us-central1-docker.pkg.dev/$PROJECT_ID/stream-watcher/ui-proxy:latest' \
          --cache-from 'us-central1-docker.pkg.dev/$PROJECT_ID/stream-watcher/ui-proxy:latest' \
          --build-arg FIREBASE_BUILD_ENV="$$FIREBASE_BUILD_ENV" \
          --build-arg VITE_FIREBASE_PROJECT_ID=$PROJECT_ID \
          .
    secretEnv:
      - 'FIREBASE_BUILD_ENV'

  # 3. Push both the versioned and latest images to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/stream-watcher/ui-proxy'

  # 4. Deploy to Cloud Run with runtime secrets for the proxy
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'stream-watcher-ui-proxy' # The name of our Cloud Run service
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/stream-watcher/ui-proxy:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--set-secrets=APP_CONFIG_JSON=app-config:latest'
      # Set run-time environment variables for the proxy server.
      # These are used by the running Node.js process, not the UI build.
      - '--set-env-vars'
      - >-
        NODE_ENV=production,
        GOOGLE_CLOUD_PROJECT=$PROJECT_ID,
        BFF_TARGET_URL=https://twitchservice-6jrv3su7zq-uc.a.run.app,
        BFF_AUDIENCE=https://twitchservice-6jrv3su7zq-uc.a.run.app,
        JWT_ISSUER=https://securetoken.google.com/$PROJECT_ID,
        JWT_AUDIENCE=$PROJECT_ID,
        JWT_JWKS_URI=https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com,
        LOG_BFF_TOKEN=true
      - '--quiet'

# Store the final image in the build results
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/stream-watcher/ui-proxy:$SHORT_SHA'

# Define which secrets to make available to the build steps
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/FIREBASE_BUILD_ENV/versions/latest
      env: 'FIREBASE_BUILD_ENV'

options:
  logging: CLOUD_LOGGING_ONLY 