steps:
  # 0. Create Artifact Registry repository if it doesn't exist
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud artifacts repositories create stream-watcher \
          --repository-format=docker \
          --location=us-central1 \
          --description="Stream Watcher repository for UI and proxy images" || true

  # 1. Install all dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install', '--legacy-peer-deps']

  # 2. Run linter
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'lint']

  # 3. Run unit tests
  - name: 'gcr.io/cloud-builders/npm'
    args: ['test']

  # 4. Build the Docker image, passing the Firebase config as a build argument
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build \
          --tag 'us-central1-docker.pkg.dev/$PROJECT_ID/stream-watcher/ui-proxy:$SHORT_SHA' \
          --build-arg FIREBASE_BUILD_ENV="$$FIREBASE_BUILD_ENV" \
          --build-arg VITE_FIREBASE_PROJECT_ID=$PROJECT_ID \
          .
    secretEnv:
      - 'FIREBASE_BUILD_ENV'

  # 5. Push the image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/stream-watcher/ui-proxy:$SHORT_SHA'

  # 6. Deploy to Cloud Run with runtime secrets for the proxy
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'stream-watcher-ui-proxy' # The name of our Cloud Run service
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/stream-watcher/ui-proxy:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--set-secrets=APP_CONFIG_JSON=app-config:latest'
      # Set run-time environment variables for the proxy server.
      # These are used by the running Node.js process, not the UI build.
      - '--set-env-vars'
      - >-
        FIREBASE_PROJECT_ID=$PROJECT_ID,
        BFF_TARGET_URL=https://twitchservice-6jrv3su7zq-uc.a.run.app,
        BFF_AUDIENCE=https://twitchservice-6jrv3su7zq-uc.a.run.app,
        JWT_ISSUER=https://securetoken.google.com/$PROJECT_ID,
        JWT_AUDIENCE=$PROJECT_ID,
        JWT_xJxWKS_URI=https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com,
        LOG_BFF_TOKEN=true
      - '--quiet'

# Store the final image in the build results
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/stream-watcher/ui-proxy:$SHORT_SHA'

# Define which secrets to make available to the build steps
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/FIREBASE_BUILD_ENV/versions/latest
      env: 'FIREBASE_BUILD_ENV'

options:
  logging: CLOUD_LOGGING_ONLY 